### ISSUE TITLE
Training code? 

### ISSUE THREAD

**Issue by antithing** [JamChaos/UE4-NeRF#1]
Hi! Great work! Thank you for making this project available!

Will you also release the code to train nerf models to load into the plugin?

Or can I train with other implementations and load the models into this plugin? 

Thanks again

**Comment by JamChaos** [comment]
Thank you for your attention! We will provide the training portion later.

**Comment by antithing** [comment]
Great! Thank you very much. Will this approach also work for close-up, high resolution datasets?

**Comment by JamChaos** [comment]
Certainly, that is perfectly fine. We store the images in host memory and perform training in blocks, utilizing storage compression methods when necessary. However, we have observed that higher resolution images require more complex models to capture finer details.

**Comment by saminkhan** [comment]
Hello there, this is a very intriguing research project! I too am interested in knowing if/when the training code will be made public.

Also, are there any plans to integrate the training process with nerfstudio?

Hoping this project hasn't been abandoned!
