### ISSUE TITLE
Integrate gaussian splatting? 

### ISSUE THREAD

**Issue by antithing** [JamChaos/UE4-NeRF#2]
Hi! Any chance you can implement this approach

https://github.com/graphdeco-inria/gaussian-splatting/tree/main

Into the unreal plugin?

It gives great results and is quick to train.

Thanks!

**Comment by tianxiaguixin002** [comment]
https://www.unrealengine.com/marketplace/en-US/product/410c8105b3aa41d38ab68660295bd7f3?lang=en-US
3D Gaussians Plugin in UE5 market, $99.99

**Comment by antithing** [comment]
Thanks!
